<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Promo;
use Carbon\Carbon;

class PromoSeeder extends Seeder
{
    public function run(): void
    {
        $promos = [
            [
                'code' => 'WELCOME10',
                'name' => 'Welcome Bonus 10%',
                'title' => 'Selamat Datang!',
                'description' => 'Diskon 10% untuk pengguna baru. Nikmati penerbangan pertamamu dengan harga spesial!',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'max_discount' => 100000,
                'min_transaction' => 300000,
                'quota' => 1000,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(30),
                'valid_until' => Carbon::now()->addMonths(6),
                'is_active' => true,
            ],
            [
                'code' => 'LIBURAN25',
                'name' => 'Liburan Diskon 25%',
                'title' => 'Liburan Seru!',
                'description' => 'Dapatkan diskon 25% untuk tiket pesawat tujuan wisata. Cocok untuk liburan akhir pekan!',
                'discount_type' => 'percentage',
                'discount_value' => 25,
                'max_discount' => 200000,
                'min_transaction' => 500000,
                'quota' => 500,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(15),
                'valid_until' => Carbon::now()->addMonths(3),
                'is_active' => true,
            ],
            [
                'code' => 'MERDEKA',
                'name' => 'Promo Merdeka',
                'title' => 'Rayakan Kemerdekaan!',
                'description' => 'Rayakan Hari Kemerdekaan dengan diskon spesial 17% untuk semua rute domestik!',
                'discount_type' => 'percentage',
                'discount_value' => 17,
                'max_discount' => 150000,
                'min_transaction' => 400000,
                'quota' => 300,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(7),
                'valid_until' => Carbon::now()->addMonths(2),
                'is_active' => true,
            ],
            [
                'code' => 'FLASH50',
                'name' => 'Flash Sale 50rb',
                'title' => 'Flash Sale!',
                'description' => 'Potongan harga Rp50.000 untuk setiap pembelian tiket. Khusus 100 pelanggan pertama setiap hari!',
                'discount_type' => 'fixed',
                'discount_value' => 50000,
                'max_discount' => 0,
                'min_transaction' => 200000,
                'quota' => 200,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(3),
                'valid_until' => Carbon::now()->addMonth(),
                'is_active' => true,
            ],
            [
                'code' => 'HEMAT100',
                'name' => 'Hemat 100rb',
                'title' => 'Hemat Besar!',
                'description' => 'Diskon Rp100.000 untuk pembelian tiket minimal Rp750.000. Jangan lewatkan kesempatan ini!',
                'discount_type' => 'fixed',
                'discount_value' => 100000,
                'max_discount' => 0,
                'min_transaction' => 750000,
                'quota' => 150,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(5),
                'valid_until' => Carbon::now()->addMonths(2),
                'is_active' => true,
            ],
            [
                'code' => 'PAYDAY',
                'name' => 'Payday Special',
                'title' => 'Gajian!',
                'description' => 'Rayakan hari gajian dengan diskon 15% untuk semua rute. Berlaku setiap tanggal 25-30!',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'max_discount' => 125000,
                'min_transaction' => 350000,
                'quota' => 400,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(10),
                'valid_until' => Carbon::now()->addMonths(4),
                'is_active' => true,
            ],
            [
                'code' => 'NEWUSER',
                'name' => 'New User Bonus',
                'title' => 'Pengguna Baru!',
                'description' => 'Selamat datang! Dapatkan potongan Rp75.000 untuk pembelian pertama kamu di drgMaskapai!',
                'discount_type' => 'fixed',
                'discount_value' => 75000,
                'max_discount' => 0,
                'min_transaction' => 250000,
                'quota' => 500,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(60),
                'valid_until' => Carbon::now()->addMonths(6),
                'is_active' => true,
            ],
            [
                'code' => 'TRAVEL2026',
                'name' => 'Travel 2026',
                'title' => 'Jelajah 2026!',
                'description' => 'Sambut tahun baru dengan diskon 20% untuk semua penerbangan di bulan Januari 2026!',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'max_discount' => 250000,
                'min_transaction' => 600000,
                'quota' => 250,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(1),
                'valid_until' => Carbon::now()->addMonths(5),
                'is_active' => true,
            ],
            [
                'code' => 'WEEKEND',
                'name' => 'Weekend Getaway',
                'title' => 'Akhir Pekan!',
                'description' => 'Diskon 12% untuk penerbangan di hari Jumat, Sabtu, dan Minggu. Liburan akhir pekan jadi lebih hemat!',
                'discount_type' => 'percentage',
                'discount_value' => 12,
                'max_discount' => 100000,
                'min_transaction' => 300000,
                'quota' => 350,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(20),
                'valid_until' => Carbon::now()->addMonths(3),
                'is_active' => true,
            ],
            [
                'code' => 'STUDENT',
                'name' => 'Student Discount',
                'title' => 'Pelajar & Mahasiswa!',
                'description' => 'Diskon khusus pelajar dan mahasiswa 15% dengan menunjukkan kartu pelajar/mahasiswa yang masih berlaku!',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'max_discount' => 80000,
                'min_transaction' => 200000,
                'quota' => 200,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(14),
                'valid_until' => Carbon::now()->addMonths(4),
                'is_active' => true,
            ],
            [
                'code' => 'FAMILY',
                'name' => 'Family Package',
                'title' => 'Liburan Keluarga!',
                'description' => 'Pesan untuk 4 orang atau lebih dan dapatkan diskon 20% untuk semua anggota keluarga!',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'max_discount' => 300000,
                'min_transaction' => 1000000,
                'quota' => 100,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(7),
                'valid_until' => Carbon::now()->addMonths(3),
                'is_active' => true,
            ],
            [
                'code' => 'BUSINESS',
                'name' => 'Business Class Promo',
                'title' => 'Bisnis Class!',
                'description' => 'Nikmati pengalaman Business Class dengan diskon 30% untuk rute domestik terpilih!',
                'discount_type' => 'percentage',
                'discount_value' => 30,
                'max_discount' => 500000,
                'min_transaction' => 1500000,
                'quota' => 50,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(2),
                'valid_until' => Carbon::now()->addMonths(2),
                'is_active' => true,
            ],
            [
                'code' => 'EARLYBIRD',
                'name' => 'Early Bird',
                'title' => 'Pesan Lebih Awal!',
                'description' => 'Pesan tiket H-30 atau lebih dan dapatkan diskon 10% ekstra!',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'max_discount' => 100000,
                'min_transaction' => 400000,
                'quota' => 300,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(30),
                'valid_until' => Carbon::now()->addMonths(6),
                'is_active' => true,
            ],
            [
                'code' => 'LASTMINUTE',
                'name' => 'Last Minute Deal',
                'title' => 'Menit Terakhir!',
                'description' => 'Booking H-1 dan dapatkan diskon 40%! Tiket terbatas, buruan pesan!',
                'discount_type' => 'percentage',
                'discount_value' => 40,
                'max_discount' => 200000,
                'min_transaction' => 500000,
                'quota' => 30,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(1),
                'valid_until' => Carbon::now()->addMonth(),
                'is_active' => true,
            ],
            [
                'code' => 'GROUP10',
                'name' => 'Group Discount 10%',
                'title' => 'Rombongan!',
                'description' => 'Pesan untuk 10 orang atau lebih dan dapatkan diskon 10% untuk seluruh anggota rombongan!',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'max_discount' => 500000,
                'min_transaction' => 2000000,
                'quota' => 50,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(10),
                'valid_until' => Carbon::now()->addMonths(4),
                'is_active' => true,
            ],
            [
                'code' => 'BIRTHDAY',
                'name' => 'Birthday Special',
                'title' => 'Selamat Ulang Tahun!',
                'description' => 'Diskon spesial 25% untuk kamu yang berulang tahun di bulan ini!',
                'discount_type' => 'percentage',
                'discount_value' => 25,
                'max_discount' => 150000,
                'min_transaction' => 300000,
                'quota' => 100,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(15),
                'valid_until' => Carbon::now()->addMonths(3),
                'is_active' => true,
            ],
            [
                'code' => 'CORPORATE',
                'name' => 'Corporate Rate',
                'title' => 'Perusahaan!',
                'description' => 'Tarif khusus korporasi dengan diskon 15% untuk pemesanan atas nama perusahaan!',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'max_discount' => 200000,
                'min_transaction' => 1000000,
                'quota' => 200,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(5),
                'valid_until' => Carbon::now()->addMonths(6),
                'is_active' => true,
            ],
            [
                'code' => 'HOLIDAY',
                'name' => 'Holiday Season',
                'title' => 'Musim Liburan!',
                'description' => 'Rayakan musim liburan dengan diskon 22% untuk semua rute domestik dan internasional!',
                'discount_type' => 'percentage',
                'discount_value' => 22,
                'max_discount' => 300000,
                'min_transaction' => 700000,
                'quota' => 150,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(3),
                'valid_until' => Carbon::now()->addMonths(2),
                'is_active' => true,
            ],
            [
                'code' => 'MIDNIGHT',
                'name' => 'Midnight Sale',
                'title' => 'Tengah Malam!',
                'description' => 'Flash sale tengah malam! Diskon 35% untuk pemesanan antara jam 00.00 - 03.00!',
                'discount_type' => 'percentage',
                'discount_value' => 35,
                'max_discount' => 250000,
                'min_transaction' => 500000,
                'quota' => 50,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(1),
                'valid_until' => Carbon::now()->addMonth(),
                'is_active' => true,
            ],
            [
                'code' => 'LOYALTY',
                'name' => 'Loyalty Reward',
                'title' => 'Pelanggan Setia!',
                'description' => 'Terima kasih telah setia! Dapatkan diskon 15% untuk pemesanan ke-5 dan seterusnya!',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'max_discount' => 100000,
                'min_transaction' => 300000,
                'quota' => 500,
                'used_count' => 0,
                'valid_from' => Carbon::now()->subDays(30),
                'valid_until' => Carbon::now()->addMonths(6),
                'is_active' => true,
            ],
        ];

        foreach ($promos as $promo) {
            Promo::updateOrCreate(
                ['code' => $promo['code']],
                $promo
            );
        }
    }
}