<?php

namespace App\Http\Controllers\Staff;

use App\Http\Controllers\Controller;
use App\Models\Booking;
use App\Models\Payment;
use App\Models\Passenger;
use App\Models\Flight;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;

class ReportExportController extends Controller
{
    /**
     * Get filtered bookings based on request parameters.
     */
    private function getFilteredBookings(Request $request)
    {
        $query = Booking::with([
            'user',
            'flight.airline',
            'flight.departureAirport',
            'flight.arrivalAirport',
            'passengers',
            'payment'
        ]);

        // Filter by date range
        if ($request->filled('date_from')) {
            $query->whereDate('created_at', '>=', $request->date_from);
        }
        if ($request->filled('date_to')) {
            $query->whereDate('created_at', '<=', $request->date_to);
        }

        // Filter by booking status
        if ($request->filled('status')) {
            $query->where('status', $request->status);
        }

        // Filter by payment status
        if ($request->filled('payment_status')) {
            $query->whereHas('payment', function ($q) use ($request) {
                $q->where('payment_status', $request->payment_status);
            });
        }

        // Filter by airline
        if ($request->filled('airline_id')) {
            $query->whereHas('flight', function ($q) use ($request) {
                $q->where('airline_id', $request->airline_id);
            });
        }

        return $query->latest()->get();
    }

    /**
     * Export to CSV (Excel-compatible)
     */
    public function exportCsv(Request $request)
    {
        $bookings = $this->getFilteredBookings($request);

        $filename = 'Laporan-Operasional-' . now()->format('Y-m-d') . '.csv';

        $headers = [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
            'Pragma' => 'no-cache',
            'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
            'Expires' => '0',
        ];

        $callback = function () use ($bookings) {
            $handle = fopen('php://output', 'w');

            // BOM for UTF-8 Excel compatibility
            fprintf($handle, chr(0xEF) . chr(0xBB) . chr(0xBF));

            // === SUMMARY SECTION ===
            fputcsv($handle, ['LAPORAN OPERASIONAL drgMaskapai']);
            fputcsv($handle, ['Tanggal Cetak: ' . now()->format('d/m/Y H:i')]);
            fputcsv($handle, ['']);
            fputcsv($handle, ['RINGKASAN']);
            fputcsv($handle, ['Total Booking', Booking::count()]);
            fputcsv($handle, ['Total Penumpang', Passenger::count()]);
            fputcsv($handle, ['Total Revenue', 'Rp' . number_format(Payment::where('payment_status', 'paid')->sum('amount'), 0, ',', '.')]);
            fputcsv($handle, ['Pending Payment', Payment::where('payment_status', 'pending')->count()]);
            fputcsv($handle, ['Confirmed Booking', Booking::where('status', 'confirmed')->count()]);
            fputcsv($handle, ['']);
            fputcsv($handle, ['']);

            // === DETAIL BOOKING ===
            fputcsv($handle, ['DETAIL BOOKING']);
            fputcsv($handle, [
                'Booking Code',
                'Customer',
                'Email',
                'Flight',
                'Airline',
                'Rute',
                'Passengers',
                'Total Price',
                'Payment Status',
                'Booking Status',
                'Booking Date'
            ]);

            foreach ($bookings as $booking) {
                $route = ($booking->flight->departureAirport->iata_code ?? '??')
                    . ' → '
                    . ($booking->flight->arrivalAirport->iata_code ?? '??');

                fputcsv($handle, [
                    $booking->booking_code,
                    $booking->user->name ?? 'N/A',
                    $booking->user->email ?? '',
                    $booking->flight->flight_number ?? 'N/A',
                    $booking->flight->airline->name ?? '',
                    $route,
                    $booking->total_passengers,
                    'Rp' . number_format($booking->total_price, 0, ',', '.'),
                    $booking->payment ? ucfirst($booking->payment->payment_status) : 'Belum Dibayar',
                    ucfirst($booking->status),
                    $booking->created_at->format('d/m/Y H:i'),
                ]);
            }

            // === FOOTER ===
            fputcsv($handle, ['']);
            fputcsv($handle, ['']);
            fputcsv($handle, ['Generated by drgMaskapai - ' . now()->format('d/m/Y H:i')]);

            fclose($handle);
        };

        return Response::stream($callback, 200, $headers);
    }

    /**
     * Print view
     */
    public function print(Request $request)
    {
        $bookings = $this->getFilteredBookings($request);

        $totalBookings = Booking::count();
        $totalPassengers = Passenger::count();
        $totalRevenue = Payment::where('payment_status', 'paid')->sum('amount');
        $pendingPayments = Payment::where('payment_status', 'pending')->count();
        $confirmedBookings = Booking::where('status', 'confirmed')->count();

        return view('staff.reports-print', compact(
            'bookings',
            'totalBookings',
            'totalPassengers',
            'totalRevenue',
            'pendingPayments',
            'confirmedBookings'
        ));
    }
}